matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      python: 3.5
    - os: linux
      dist: xenial
      sudo: required
      python: 3.6
    - os: osx
      osx_image: xcode_9.2
      language: generic
    - os: osx
      language: generic
install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew install python3 ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then pip3 install tox ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then pip3 install tox-travis ;fi 
script:
    - echo "skip tox for build testing"
after_success:
    - if [ "$TRAVIS_BRANCH" = "example-travis-config" ]; then echo "TRAVIS BUILD " ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew install gettext ; fi
    - pip3 install pyinstaller pycurl requests PyQt5
    - contrib/make_locale
    - contrib/make_packages
    - pip install trezor keepkey btchip-python -t packages
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then contrib/make_osx; else  echo "test over" ; fi
